### PR TITLE
Step one: reduce DNS requests

### PR DESCRIPTION
**Pull request by hkatzdev**
The most obvious culprit of requests is the layout template. This deals with most of the requests in there. I used url_for('web.static', filename= style to link the local files. While I saw a css and javascript folder, there were conflicts with some of the files that used .. to find thier fonts. Instead of modifying all of these files, I just put all the libraries into thier own folder and renamed the folders to match the urls. Material Design for Bootstrap is not included, as the only download I could find was for 4.10, and will be included in a seperate commit.

### CODE REVIEW

**Comment by hkatzdev** [comment]
While this is failing, so was the build 5 days ago - https://travis-ci.org/sugarlabs/aslo-v3/builds/447001187.

**Review by vipulgupta2048 — COMMENTED** [review]
Thanks, @HarrisonLKatz for making the pull request to fix the issue. Some comments :-
1. Can you post a before and after of the DNS queries being made to show comparison and the improvements shown through the changes that were made. 
2. Refactoring your commit messages to be small and informative using the command `git commit --amend` for the people reading the commit history later. 
3. @jatindhankar Can you check & rectify the reason for why the build is failing, Travis dashboard isn't able to load on my browser even after multiple reloads

**Comment by quozl** [comment]
https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits is a checklist for writing commit messages.  The text of 74e57bb is great as a pull request comment though.

**Comment by hkatzdev** [comment]
The Add external libraries to the static folder. commit should be the right one, I think I messed up on the git commit -amend command, and it made me use git pull.

**Comment by hkatzdev** [comment]
I think I am going to just open up another PR request once I'm done and redo my git commands - I'm still learning git, and I think I messed up by trying to use multiple branches in the same folder which is making it hard for me to do proper commits. Thank you for reviewing this, and I'll post my new one shortly.

**Comment by quozl** [comment]
No worries.  I know how you feel.  Often there are five to ten ways to do any specific task in git.  One method is to backup your repository before you do things, then see what it is you've done usual visualisers such as `gitk`, or `git log`.  My preference is `magit` inside `emacs`.

**Comment by hkatzdev** [comment]
I have made an improved pull request here --> https://github.com/sugarlabs/aslo-v3/pull/10 - Thank you all for helping me with this one and for giving me tips on how to improve my next one!

**Pull request closed without merging**
