### PR TITLE
Changed some of the icons from png to svg

### PR DESCRIPTION
**Pull request by Joeloedinho**
Changed some of the icons from png to svg

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@jatindhankhar can you please let @Joeloedinho where have you placed the .png ?

**Comment by jatindhankhar** [comment]
Hi @Joeloedinho ,
Thank you for the contribution.
It looks like you are trying to add svg icons for the activities itself, correct me if I am getting it wrong :)

Icon for an activity  is pulled from it's bundle (https://github.com/sugarlabs/aslo-v3/blob/master/aslo/api/img.py#L11 )

 Then stored inside the mongodb as hash (https://github.com/sugarlabs/aslo-v3/blob/master/aslo/models/activity.py#L25) 

And then rendered back as svg  (https://github.com/sugarlabs/aslo-v3/blob/master/aslo/web/templates/elements/activity_detail_card.html#L6)

So, if you want to add/replace icons for the same, it will be by adding the svg icons for the respective activities

**Comment by Joeloedinho** [comment]
OK thanks, i'm trying to change the icons but can you please guide me on how to change the icons
like how to add the svg icons to the respective activities

**Comment by quozl** [comment]
@Joeloedinho, you've been led into a misunderstanding.  @jaskirat2000 in #sugar suggested you had to design the SVGs.  This is untrue.  The SVGs are part of the activity bundles already.  No SVG design is ncessary.   @jatindhankhar has shown above how they are extracted from the bundles.  They are to be used in the web pages shown by the aslo-v3 application.

As an example, you've set the Log activity icon to;
* https://github.com/sugarlabs/aslo-v3/blob/cbd3b62ba87445bc701b4958289aedd0b63820fa/aslo/web/static/img/log.svg

But the actual icon in the most recent release is;
* https://github.com/sugarlabs/log-activity/blob/master/activity/activity-log.svg

The actual icons from the activities must be presented, and they must be presented as SVG rather than PNG.  The aslo-v3 application is incomplete, and this is one of the ways it is incomplete.

A pull request to fix this problem must;
* remove the temporary PNG files,
* not add any SVG files to the repository, and;
* generate the SVG files from the database dynamically.

If you've been deceived, I'd say the causes are;
* an incomplete task description,
* people who want to help but read the incomplete description just like you did.

You could have reduced this by asking your question of more people, such as using sugar-devel@ mailing list on lists.sugarlabs.org.  IRC contains only very few people.

Hope that helps.  Looking forward to your next try,

**Comment by ayushnagar123** [comment]
Hi, everyone sorry to interrupt, I am ayushnagar123(Ayush Nagar), I mainly work in python and nodejs. I am looking forward to participating in GSOC 2019 with sugarlabs. If there is no issue, as I am knowing this is a GCI related task as I am active at IRC channel and observing the proceedings of the organisation, I feel I can help @Joeloedinho in this task.

**Comment by Joeloedinho** [comment]
OK thanks ayushnagar I will be so happy if you help me

**Comment by ayushnagar123** [comment]
Thanks, As per I have understood the issue, all svg files are stored in mongodb database. 
These are the things you need to do complete this task:-
1. There are temporary png file which are stored in somewhere which are presently being served as an icon which are blur.
2. The database server used by the developer is the mongodb in which svg files are stored in the form of hash so you need not to add any new svg files into the folders as they are already present in database.
https://github.com/sugarlabs/aslo-v3/blob/master/aslo/api/img.py#L11 )
This line shows the path from where(repo_path) the image and which icon(icon_name) needs to be fetched
https://github.com/sugarlabs/aslo-v3/blob/master/aslo/models/activity.py#L25
Here this line shows that the image is storing in form of a hash in the database.
3. The main work you need to do is to right a script in python which will fetch these images as per where which image is to be displayed and serve these images with respect to the content. At present the images used are temporary png file which are blur.
https://github.com/sugarlabs/aslo-v3/blob/master/aslo/web/templates/elements/activity_detail_card.html#L6)
Here is the place where the content would be served and displayed.
The changes you will be needed to make are:-
(1) To add the code which will fetch these files.
(2) You may need to make some changes in the template used.
Go through the code first which is related to content. Try to make the code to serve the images.
The requirement you need to do this task are:-
(i) The knowledge of hashes which wil help you to fetch the images. If you dont know what are hashes you can refer to the wikipedia link or from whereever you feel like. My personal choice is https://www.geeksforgeeks.org/hashing-set-1-introduction/  .
(ii) You must be able to understand what the perticular line of code do.
Hope I am able to solve atleast any one of your doubt. Do inform of you find this helpful.Hopping for your success in GCI 2018:)

**Comment by Joeloedinho** [comment]
Thanks so much ayushnagar123  I will try my best on this task at least I know what I'm to do now

**Comment by quozl** [comment]
@ayushnagar123, thanks for speaking up.

**Comment by vipulgupta2048** [comment]
@ayushnagar123 The student working on the task as been unassigned since he will not be able to continue with solving this issue. Wanna go ahead and make a PR for the same?

**Comment by quozl** [comment]
@Joeloedinho, thanks for trying, and sorry that we stuffed you around.  Sugar Labs is very diverse and doesn't always communicate well.  We need to try harder, and be more open with ourselves. :grinning:

**Comment by ayushnagar123** [comment]
@vipulgupta2048 sure, i will try my best to do it. 😀

**Pull request closed without merging**
